# Generated by Django 3.2.9 on 2022-01-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='amount_invested',
            field=models.IntegerField(default=10),
        ),
    ]
